name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - ocelhay
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please make sure **NOT TO INCLUDE ANY PII INFORMATION** in the text or in the screenshots.
  - type: dropdown
    id: app
    attributes:
      label: App/Dashboard
      description: What app/dashboard are you running?
      options:
        - ABCD Metrics
        - ABCD RA Tools
        - HBCD TLFB
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running?
      options:
        - production version
        - development version (URL ends with `-dev`)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Describe steps to reproduce the behavior.
      placeholder: Include steps to reproduce the behavior.
        1. Select the tab '...'
        2. Use this selection of filters '...'
        3. Run '...'
        4. See error '...'
    validations:
      required: true
